# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-10 07:04
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asmuo',
            fields=[
                ('pavadinimas', models.CharField(max_length=100)),
                ('adresas', models.CharField(max_length=100)),
                ('asmens_kodas', models.CharField(max_length=100, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(regex='^[0-9]{11}$')])),
                ('PVM_moketojo_kodas', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(regex='^LT[0-9]{12}$')])),
            ],
        ),
        migrations.CreateModel(
            name='PVMIrasas',
            fields=[
                ('iraso_nr', models.AutoField(primary_key=True, serialize=False)),
                ('prekes_pavadinimas', models.CharField(max_length=100)),
                ('matavimo_vnt', models.CharField(max_length=100)),
                ('kaina_be_PVM', models.DecimalField(decimal_places=2, max_digits=8)),
                ('suma_be_PVM', models.DecimalField(decimal_places=2, max_digits=8)),
                ('PVM_tarifas', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('PVM_suma', models.DecimalField(decimal_places=2, max_digits=8)),
                ('suma_viso', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='PVMSask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serija', models.CharField(max_length=3)),
                ('nr', models.CharField(max_length=3)),
                ('data', models.DateField(default=datetime.date.today)),
                ('suma_zodziais', models.CharField(max_length=100)),
                ('israses_asmuo', models.CharField(max_length=100)),
            ],
        ),
    ]
