# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-10 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180310_0938'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Asmuo',
        ),
        migrations.DeleteModel(
            name='PVMIrasas',
        ),
        migrations.RemoveField(
            model_name='pvmsask',
            name='suma_zodziais',
        ),
        migrations.AddField(
            model_name='pvmsask',
            name='pardavejas',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AddField(
            model_name='pvmsask',
            name='pardavejo_PVM_moketojo_kodas',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AddField(
            model_name='pvmsask',
            name='pardavejo_adresas',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AddField(
            model_name='pvmsask',
            name='pardavejo_asmens_kodas',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AddField(
            model_name='pvmsask',
            name='pirkejas',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AddField(
            model_name='pvmsask',
            name='pirkejo_PVM_moketojo_kodas',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AddField(
            model_name='pvmsask',
            name='pirkejo_adresas',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AddField(
            model_name='pvmsask',
            name='pirkejo_asmens_kodas',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
    ]
