# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-10 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180310_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='PVMIrasas',
            fields=[
                ('iraso_nr', models.AutoField(primary_key=True, serialize=False)),
                ('prekes_pavadinimas', models.CharField(max_length=100)),
                ('matavimo_vnt', models.CharField(max_length=100)),
                ('kaina_be_PVM', models.DecimalField(decimal_places=2, max_digits=8)),
                ('suma_be_PVM', models.DecimalField(decimal_places=2, max_digits=8)),
                ('PVM_tarifas', models.FloatField()),
                ('PVM_suma', models.DecimalField(decimal_places=2, max_digits=8)),
                ('suma_viso', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.AddField(
            model_name='pvmsask',
            name='prekes',
            field=models.ManyToManyField(to='app.PVMIrasas'),
        ),
    ]
