# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-10 12:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180310_1326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pvmirasas',
            old_name='kaina_be_PVM',
            new_name='vnt_kaina_be_PVM',
        ),
    ]
