# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-10 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180310_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='pvmirasas',
            name='kiekis',
            field=models.IntegerField(default=1, max_length=100),
        ),
        migrations.AlterField(
            model_name='pvmirasas',
            name='PVM_suma',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=8),
        ),
        migrations.AlterField(
            model_name='pvmirasas',
            name='PVM_tarifas',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='pvmirasas',
            name='matavimo_vnt',
            field=models.CharField(default='not NULL', max_length=100),
        ),
        migrations.AlterField(
            model_name='pvmirasas',
            name='prekes_pavadinimas',
            field=models.CharField(default='not NULL', max_length=100),
        ),
        migrations.AlterField(
            model_name='pvmirasas',
            name='suma_be_PVM',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=8),
        ),
        migrations.AlterField(
            model_name='pvmirasas',
            name='suma_viso',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=8),
        ),
        migrations.AlterField(
            model_name='pvmirasas',
            name='vnt_kaina_be_PVM',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=8),
        ),
        migrations.AlterField(
            model_name='pvmsask',
            name='pardavejas',
            field=models.CharField(default='not NULL', max_length=100),
        ),
        migrations.AlterField(
            model_name='pvmsask',
            name='pardavejo_PVM_moketojo_kodas',
            field=models.CharField(default='not NULL', max_length=100),
        ),
        migrations.AlterField(
            model_name='pvmsask',
            name='pardavejo_adresas',
            field=models.CharField(default='not NULL', max_length=100),
        ),
        migrations.AlterField(
            model_name='pvmsask',
            name='pardavejo_asmens_kodas',
            field=models.CharField(default='not NULL', max_length=100),
        ),
        migrations.AlterField(
            model_name='pvmsask',
            name='pirkejas',
            field=models.CharField(default='not NULL', max_length=100),
        ),
        migrations.AlterField(
            model_name='pvmsask',
            name='pirkejo_PVM_moketojo_kodas',
            field=models.CharField(default='not NULL', max_length=100),
        ),
        migrations.AlterField(
            model_name='pvmsask',
            name='pirkejo_adresas',
            field=models.CharField(default='not NULL', max_length=100),
        ),
        migrations.AlterField(
            model_name='pvmsask',
            name='pirkejo_asmens_kodas',
            field=models.CharField(default='not NULL', max_length=100),
        ),
    ]
