# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-12 16:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20180310_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pvmsask',
            name='prekes',
        ),
        migrations.AddField(
            model_name='pvmirasas',
            name='PVM_sask',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.PVMSask'),
        ),
        migrations.AlterField(
            model_name='pvmsask',
            name='pardavejas',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='pvmsask',
            name='pardavejo_PVM_moketojo_kodas',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='pvmsask',
            name='pardavejo_adresas',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='pvmsask',
            name='pardavejo_asmens_kodas',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='pvmsask',
            name='pirkejas',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='pvmsask',
            name='pirkejo_PVM_moketojo_kodas',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='pvmsask',
            name='pirkejo_adresas',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='pvmsask',
            name='pirkejo_asmens_kodas',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
