# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-12 17:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20180312_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pvmirasas',
            name='PVM_saskaita',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.PVMSask'),
        ),
    ]
