# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-13 14:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20180313_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nurasymoaktas',
            name='atsakingas_asmuo',
        ),
    ]
