# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-13 14:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_remove_nurasymoaktoirasas_nurasymo_aktas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NurasymoAktas',
        ),
    ]
