# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-13 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20180313_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pvmsask',
            name='nr',
            field=models.CharField(default='AAA', max_length=3),
        ),
        migrations.AlterField(
            model_name='pvmsask',
            name='pardavejas',
            field=models.CharField(default='Jonas Jonaitis', max_length=100),
        ),
        migrations.AlterField(
            model_name='pvmsask',
            name='pardavejo_PVM_moketojo_kodas',
            field=models.CharField(default='8541224566', max_length=100),
        ),
        migrations.AlterField(
            model_name='pvmsask',
            name='pardavejo_adresas',
            field=models.CharField(default='Gargzdu pr. 8-127', max_length=100),
        ),
        migrations.AlterField(
            model_name='pvmsask',
            name='pardavejo_asmens_kodas',
            field=models.CharField(default='39656237415', max_length=100),
        ),
        migrations.AlterField(
            model_name='pvmsask',
            name='pirkejas',
            field=models.CharField(default='Petras Petraitis', max_length=100),
        ),
        migrations.AlterField(
            model_name='pvmsask',
            name='pirkejo_PVM_moketojo_kodas',
            field=models.CharField(default='8541224566', max_length=100),
        ),
        migrations.AlterField(
            model_name='pvmsask',
            name='pirkejo_adresas',
            field=models.CharField(default='Pievu g. 7-18', max_length=100),
        ),
        migrations.AlterField(
            model_name='pvmsask',
            name='pirkejo_asmens_kodas',
            field=models.CharField(default='39612656985', max_length=100),
        ),
        migrations.AlterField(
            model_name='pvmsask',
            name='serija',
            field=models.CharField(default='123', max_length=3),
        ),
    ]
