# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-13 15:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_remove_pvmsask_nurasymo_aktas'),
    ]

    operations = [
        migrations.AddField(
            model_name='pvmsask',
            name='nurasymo_aktas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.NurasymoAktas'),
        ),
        migrations.AlterField(
            model_name='pvmsask',
            name='israses_asmuo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
