# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-13 15:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_auto_20180313_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pvmsask',
            name='israses_asmuo',
        ),
        migrations.RemoveField(
            model_name='pvmsask',
            name='nurasymo_aktas',
        ),
    ]
