# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-13 15:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_auto_20180313_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pvmirasas',
            name='PVM_saskaita',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.PVMSask'),
        ),
    ]
