# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-13 15:58
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0034_auto_20180313_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='KomisijosNarys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vardas', models.CharField(default=None, max_length=100)),
                ('pavarde', models.CharField(default=None, max_length=100)),
                ('funkcija', models.CharField(default=None, max_length=100)),
                ('pareigos', models.CharField(default=None, max_length=100)),
                ('yra_pirmininkas', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='NurasymoAktas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=datetime.date.today)),
                ('nr', models.CharField(default=None, max_length=100)),
                ('viso_suma', models.FloatField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='NurasymoAktoIrasas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mat_vertybes_pav', models.CharField(default=None, max_length=100)),
                ('mato_vnt', models.CharField(default=None, max_length=100)),
                ('kiekis', models.FloatField(default=None)),
                ('kaina', models.FloatField(default=None)),
                ('suma_su_PVM', models.FloatField(default=None)),
                ('panaudojimo_tikslas', models.CharField(default=None, max_length=100)),
                ('nurasymo_aktas', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.NurasymoAktas')),
            ],
        ),
        migrations.AddField(
            model_name='pvmsask',
            name='israses_asmuo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pvmirasas',
            name='nurasymo_aktas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.NurasymoAktas'),
        ),
        migrations.AddField(
            model_name='pvmsask',
            name='nurasymo_aktas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.NurasymoAktas'),
        ),
    ]
