# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-13 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_auto_20180313_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurasymoaktas',
            name='viso_suma',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
