# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-14 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_auto_20180313_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurasymoaktas',
            name='PVM_saskaitos',
            field=models.ManyToManyField(default=None, related_name='thename', to='app.PVMSask'),
        ),
    ]
