# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-15 10:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_auto_20180314_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurasymoaktoirasas',
            name='kiekis',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='nurasymoaktoirasas',
            name='mat_vertybes_pav',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='nurasymoaktoirasas',
            name='mato_vnt',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='nurasymoaktoirasas',
            name='nurasymo_aktas',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.NurasymoAktas'),
        ),
        migrations.AlterField(
            model_name='nurasymoaktoirasas',
            name='panaudojimo_tikslas',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='nurasymoaktoirasas',
            name='suma_su_PVM',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
