# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-15 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_auto_20180315_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurasymoaktoirasas',
            name='kaina',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
