# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-15 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_auto_20180315_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='nurasymoaktas',
            name='is_submited',
            field=models.BooleanField(default=False),
        ),
    ]
