# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-17 22:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_auto_20180317_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pvmirasas',
            name='nurasymo_aktas',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.NurasymoAktas'),
        ),
    ]
