# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-18 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_auto_20180318_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='pareigos',
            field=models.CharField(choices=[('ATSAKINGAS_ASMUO', 'Atsakingas asmuo'), ('KOMISIJOS NARYS PIRMININKAS', 'Komisijos narys pirmininkas'), ('KOMISIJOS NARYS', 'Komisijos narys'), ('DIREKTORIUS', 'Direktorius')], default='DIREKTORIUS', max_length=100),
        ),
    ]
