# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-18 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_auto_20180318_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='darbo_istaiga',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='pareigos',
            field=models.CharField(blank=True, choices=[('ATSAKINGAS_ASMUO', 'Atsakingas asmuo'), ('KOMISIJOS NARYS PIRMININKAS', 'Komisijos narys pirmininkas'), ('KOMISIJOS NARYS', 'Komisijos narys'), ('DIREKTORIUS', 'Direktorius')], default='DIREKTORIUS', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='pavarde',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='vardas',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
