# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-18 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_auto_20180318_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='pareigos',
            field=models.CharField(blank=True, choices=[('ATSAKINGAS ASMUO', 'Atsakingas asmuo'), ('KOMISIJOS NARYS PIRMININKAS', 'Komisijos narys pirmininkas'), ('KOMISIJOS NARYS', 'Komisijos narys'), ('DIREKTORIUS', 'Direktorius'), ('ADMIN', 'Admin')], default=None, max_length=100, null=True),
        ),
    ]
