# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-18 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_nurasymoaktas_komisijos_pirmininkas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurasymoaktas',
            name='viso_suma',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='nurasymoaktoirasas',
            name='kaina',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='nurasymoaktoirasas',
            name='kiekis',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='nurasymoaktoirasas',
            name='suma_su_PVM',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='pvmirasas',
            name='PVM_suma',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=12),
        ),
        migrations.AlterField(
            model_name='pvmirasas',
            name='kiekis',
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='pvmirasas',
            name='suma_be_PVM',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=12),
        ),
        migrations.AlterField(
            model_name='pvmirasas',
            name='suma_viso',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=12),
        ),
        migrations.AlterField(
            model_name='pvmirasas',
            name='vnt_kaina_be_PVM',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=12),
        ),
    ]
