# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-18 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_auto_20180318_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='nurasymoaktoirasas',
            name='max_kiekis',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
