# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-18 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_nurasymoaktoirasas_max_kiekis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pvmirasas',
            name='PVM_tarifas',
            field=models.DecimalField(decimal_places=2, default=21, max_digits=12),
        ),
    ]
