# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-18 16:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_auto_20180318_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nurasymoaktoirasas',
            name='max_kiekis',
        ),
    ]
