# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-18 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_remove_nurasymoaktoirasas_max_kiekis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurasymoaktoirasas',
            name='kaina',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='nurasymoaktoirasas',
            name='suma_su_PVM',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
