# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-18 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0054_auto_20180318_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurasymoaktoirasas',
            name='kaina',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='nurasymoaktoirasas',
            name='suma_su_PVM',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, null=True),
        ),
    ]
