# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-18 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_auto_20180318_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pvmirasas',
            name='PVM_tarifas',
            field=models.IntegerField(default=21),
        ),
    ]
