# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-22 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0058_nurasymoaktoirasas_pvm_iraso_pk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pvmsask',
            name='serija',
            field=models.CharField(default='123', max_length=3, unique=True),
        ),
    ]
