# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-22 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0059_auto_20180322_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='pareigos',
            field=models.CharField(choices=[('ATSAKINGAS ASMUO', 'Atsakingas asmuo'), ('KOMISIJOS NARYS PIRMININKAS', 'Komisijos narys pirmininkas'), ('KOMISIJOS NARYS', 'Komisijos narys'), ('DIREKTORIUS', 'Direktorius'), ('ADMIN', 'Admin')], default='ADMIN', max_length=100, null=True),
        ),
    ]
